Notes mode

diff --git a/mangle b/mangle
--- a/mangle
+++ b/mangle
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 less_command='| less $less_no_init -aiF -Ps"Manual page\: $man_page (?ltline %lt?L/%L.:byte %bB?s/%s..? (END):?pB %pB\%..)"'
-grepopts='-i'  # grep case-insensitive by default
+grepopts='-i'           # grep case-insensitive by default
+notesmode=0             # show personal notes instead of man page if set to 1
+notes_indicator='notes'  # If this is the first search pattern, display personal notes instead of man page
+notesdir=~/.local/share/manglenotes
 
 # Get section
 if [[ $1 =~ [0-9]+ ]]
@@ -12,6 +15,7 @@ fi
 
 # Find the longest set of args that gets a man page
 man_page=("$@")
+notes_page=("$@")
 while ! command man -w $(echo "${man_page[@]}" | tr " " "-") &>/dev/null
 do
     patterns+=( ${man_page[-1]} )
@@ -23,7 +27,27 @@ done
 # plain string
 man_page="${man_page[@]}"
 
-# Build grep command
+# If there's no matching man page
+if [ -z "$man_page" ]; then
+	if [ "${#notes_page[@]}" -lt 2 ]; then
+		echo "Error: no man page for '${notes_page[0]}'"
+		exit 1
+	elif [ "${notes_page[1]}" != "$notes_indicator" ]; then
+		echo "Error: no man page for '${notes_page[0]}'."
+		exit 1
+	else
+		# Notes mode
+		man_page="${notes_page[0]}"
+		notes_page=("${notes_page[@]:1}")
+		patterns=()
+		while [ "${#notes_page[@]}" -gt 0 ]; do
+			patterns+=( "${notes_page[-1]}" )
+			unset notes_page[-1]
+		done
+	fi
+fi
+
+# Process special "patterns"
 if [[ ${patterns[@]} ]]
 then
 	# If first "pattern" is 'opt' then add some regex to next pattern (should allow more than one pattern to be converted this way)
@@ -39,19 +63,31 @@ then
 			# opt by itself just looks for any leading hyphen
 			patterns[-1]="'^ *-[A-Z]*[ ,]'"
 		fi
+	elif [ "${patterns[-1]}" = "$notes_indicator" ]; then
+		# Enter notes mode
+		notesmode=1
+		unset patterns[-1]
 	fi
+fi
 
+# Build grep command
+if [[ ${patterns[@]} ]]; then
     grep_command="| grep $grepopts -C4 --color=always ${patterns[@]/#/-e }"
 fi
 
 # Patterns given on command line, so give grep version
-if [[ ${patterns[@]} ]]; then
-	# Show man page with search patterns highlighted, piped through less
-	command="command man $section $man_page $grep_command"
+if [ "$notesmode" -ne 1 ]; then
+	if [[ ${patterns[@]} ]]; then
+		# Show man page with search patterns highlighted, piped through less
+		command="command man $section $man_page $grep_command"
+	else
+		# If no patterns, don't pipe through less (to keep man page TERMCAP coloring)
+		command="command man $section $man_page"
+		less_command=''
+	fi
 else
-	# If no patterns, don't pipe through less (to keep man page TERMCAP coloring)
-	command="command man $section $man_page"
-	less_command=''
+	# Notes mode
+	command="command cat $notesdir/$man_page $grep_command"  # Still ok if spaces in $notesdir?
 fi
 
 # Check screen and output sizes (only do this if actually piping into less. Reason: wc chokes on mpv's man page)
